// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSQzF4ZqSj71X5548r_GVbQTmPrbWPbEE',
    appId: '1:37529669772:web:98320d33552b7b4c722ba9',
    messagingSenderId: '37529669772',
    projectId: 'ai-hackathon-app',
    authDomain: 'ai-hackathon-app.firebaseapp.com',
    storageBucket: 'ai-hackathon-app.appspot.com',
    measurementId: 'G-N6BJ5ZBFJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTYcUdml0mAzh4reECQEEI_H47H0F8bJM',
    appId: '1:37529669772:android:6fc5219014b0c0e4722ba9',
    messagingSenderId: '37529669772',
    projectId: 'ai-hackathon-app',
    storageBucket: 'ai-hackathon-app.appspot.com',
  );
}
